spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always

app:
  datasource:
    jdbc-url: jdbc:postgresql://database-1.cylxalprx62b.eu-west-1.rds.amazonaws.com:5432/student
    username: postgres
    password: 21949118Uk
    pool-size: 30